# 4. Practicing Scikit-Learn Syntax
Let's get good with Scikit-learn during this notebook.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.options.display.max_columns = 100
%matplotlib inline

heart = pd.read_csv('../data/heart.csv').dropna()
heart

age     sex    chest_pain  rest_bp  chol  fbs  \
0     63    Male       typical      145   233    1   
1     67    Male  asymptomatic      160   286    0   
2     67    Male  asymptomatic      120   229    0   
3     37    Male    nonanginal      130   250    0   
4     41  Female    nontypical      130   204    0   
5     56    Male    nontypical      120   236    0   
6     62  Female  asymptomatic      140   268    0   
7     57  Female  asymptomatic      120   354    0   
8     63    Male  asymptomatic      130   254    0   
9     53    Male  asymptomatic      140   203    1   
10    57    Male  asymptomatic      140   192    0   
11    56  Female    nontypical      140   294    0   
12    56    Male    nonanginal      130   256    1   
13    44    Male    nontypical      120   263    0   
14    52    Male    nonanginal      172   199    1   
15    57    Male    nonanginal      150   168    0   
16    48    Male    nontypical      110   229    0   
17    54    Male  asymptomatic      140   239    0   
18    48  Female    nonanginal      130   275    0   
19    49    Male    nontypical      130   266    0   
20    64    Male       typical      110   211    0   
21    58  Female       typical      150   283    1   
22    58    Male    nontypical      120   284    0   
23    58    Male    nonanginal      132   224    0   
24    60    Male  asymptomatic      130   206    0   
25    50  Female    nonanginal      120   219    0   
26    58  Female    nonanginal      120   340    0   
27    66  Female       typical      150   226    0   
28    43    Male  asymptomatic      150   247    0   
29    40    Male  asymptomatic      110   167    0   
..   ...     ...           ...      ...   ...  ...   
271   66    Male  asymptomatic      160   228    0   
272   46    Male  asymptomatic      140   311    0   
273   71  Female  asymptomatic      112   149    0   
274   59    Male       typical      134   204    0   
275   64    Male       typical      170   227    0   
276   66  Female    nonanginal      146   278    0   
277   39  Female    nonanginal      138   220    0   
278   57    Male    nontypical      154   232    0   
279   58  Female  asymptomatic      130   197    0   
280   57    Male  asymptomatic      110   335    0   
281   47    Male    nonanginal      130   253    0   
282   55  Female  asymptomatic      128   205    0   
283   35    Male    nontypical      122   192    0   
284   61    Male  asymptomatic      148   203    0   
285   58    Male  asymptomatic      114   318    0   
286   58  Female  asymptomatic      170   225    1   
288   56    Male    nontypical      130   221    0   
289   56    Male    nontypical      120   240    0   
290   67    Male    nonanginal      152   212    0   
291   55  Female    nontypical      132   342    0   
292   44    Male  asymptomatic      120   169    0   
293   63    Male  asymptomatic      140   187    0   
294   63  Female  asymptomatic      124   197    0   
295   41    Male    nontypical      120   157    0   
296   59    Male  asymptomatic      164   176    1   
297   57  Female  asymptomatic      140   241    0   
298   45    Male       typical      110   264    0   
299   68    Male  asymptomatic      144   193    1   
300   57    Male  asymptomatic      130   131    0   
301   57  Female    nontypical      130   236    0   

                          rest_ecg  max_hr  exang  old_peak  slope   ca  \
0    left ventricular hypertrophy      150      0       2.3      3  0.0   
1    left ventricular hypertrophy      108      1       1.5      2  3.0   
2    left ventricular hypertrophy      129      1       2.6      2  2.0   
3                           normal     187      0       3.5      3  0.0   
4    left ventricular hypertrophy      172      0       1.4      1  0.0   
5                           normal     178      0       0.8      1  0.0   
6    left ventricular hypertrophy      160      0       3.6      3  2.0   
7                           normal     163      1       

# Let's build many different models from different parts of the library slowly adding more features
* Let's build decision trees, random forests, K-Nearest Neighbors and Support vector machines:
* Predict, then Score, and write down your scores

# Scores
* baseline - 54
* logistic regression w/ max_hr - 67
* knn w/ max_hr - 74
* knn w/ 3 vars - 75

In [3]:
X = heart['max_hr'].values.reshape(-1, 1)
y = heart['disease'].values

In [5]:
X[:4]

array([[150],
       [108],
       [129],
       [187]])

In [7]:
y[:4]

array([0, 1, 1, 0])

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
knc = KNeighborsClassifier()

In [10]:
knc.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [11]:
knc.score(X, y)

0.7407407407407407

In [12]:
heart.head()

age     sex    chest_pain  rest_bp  chol  fbs  \
0   63    Male       typical      145   233    1   
1   67    Male  asymptomatic      160   286    0   
2   67    Male  asymptomatic      120   229    0   
3   37    Male    nonanginal      130   250    0   
4   41  Female    nontypical      130   204    0   

                        rest_ecg  max_hr  exang  old_peak  slope   ca  \
0  left ventricular hypertrophy      150      0       2.3      3  0.0   
1  left ventricular hypertrophy      108      1       1.5      2  3.0   
2  left ventricular hypertrophy      129      1       2.6      2  2.0   
3                         normal     187      0       3.5      3  0.0   
4  left ventricular hypertrophy      172      0       1.4      1  0.0   

         thal  disease  
0       fixed        0  
1      normal        1  
2  reversable        1  
3      normal        0  
4      normal        0

In [13]:
X = heart[['rest_bp', 'chol', 'max_hr']].values
X[:5]

array([[145, 233, 150],
       [160, 286, 108],
       [120, 229, 129],
       [130, 250, 187],
       [130, 204, 172]])

In [15]:
knc.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [16]:
knc.score(X, y)

0.7474747474747475

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
dtc = DecisionTreeClassifier()

In [19]:
dtc.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [20]:
dtc.score(X, y)

1.0